### ISSUE TITLE
Update dependabot to ignore the src folder

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/feluda#554]
The task of this issue is to update the [`dependabot.yml`](https://github.com/tattle-made/feluda/blob/main/.github/dependabot.yml) file to ignore the `src/` folder. As the src/ folder now contains old code that is not actively maintained. 
Also change the GitHub actions section update to mostly as we don't need too frequent updates
https://github.com/tattle-made/feluda/blob/8e82cbceca5e3df869228b1c6c71311602d0154c/.github/dependabot.yml#L20-L25

An added bonus would be to look into how to close all old dependabot PRs

**Comment by omkar-334** [comment]
Hi @aatmanvaidya , currently I've changed the root folder from `src` to `/` and changed the update interval from `weekly` to `monthly.`   

Here is the commit - https://github.com/tattle-made/feluda/compare/main...omkar-334:feluda:update-dependabot

One doubt I have is, does dependabot recursively scan the root folder or only the root folder, or root folder and first layer?  
Based on this we can add separate sections for `ignore` like - 
```
  # Ignore Docker updates in /src
  - package-ecosystem: "docker"
    directory: "/src"
    ignore:
      - dependency-name: "*"

  # Ignore Pip updates in /src
  - package-ecosystem: "pip"
    directory: "/src"
    ignore:
      - dependency-name: "*"
```

**Comment by omkar-334** [comment]
Hi @aatmanvaidya , I tested different configs on my fork and these are the results - 

So first I enabled dependabot on my fork and i got the pull requests from it.  
Then I committed the new dependabot.yml, setting `/src` to `ignore`.  

1. Explicitly ignoring `src` folder - 
```
version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"

  # Ignore Docker updates in /src
  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"

  # Enable version updates for Pip
  - package-ecosystem: "pip"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"

  # Ignore Pip updates in /src
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"

  # Enable version updates for github-actions
  - package-ecosystem: "github-actions"
    # Look for a `Dockerfile` in the `root` directory
    directory: ".github/workflows"
    # Check for updates once a month
    schedule:
      interval: "monthly"
```

This configuration closed all existing PRs which focused on the `/src` directory - You can see the closed PRs [here](https://github.com/omkar-334/feluda/pulls?q=is%3Apr+is%3Aclosed)

But this config may lead to some edgecases. See the active PRs [here](https://github.com/omkar-334/feluda/pulls)
Out of 6 new PRs, 5 are of `/` and ` is for `/src`.

2. The second config does not mention `/src` at all. 
```
version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"

  # Enable version updates for Pip
  - package-ecosystem: "pip"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"

  # Enable version updates for github-actions
  - package-ecosystem: "github-actions"
    # Look for a `Dockerfile` in the `root` directory
    directory: ".github/workflows"
    # Check for updates once a month
    schedule:
      interval: "monthly"
```
So after I had committed this, no new PRs were generated. Which means it's working properly.   
But since I did'nt mention `src` as `ignore`, the old `src` related PR was not closed automatically
